/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.oracle.hackson.webapp.Schema.avrotojava;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Ping extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1832990667691969283L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Ping\",\"namespace\":\"com.oracle.hackson.webapp.Schema.avrotojava\",\"fields\":[{\"name\":\"reset\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Ping> ENCODER =
      new BinaryMessageEncoder<Ping>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Ping> DECODER =
      new BinaryMessageDecoder<Ping>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Ping> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Ping> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Ping>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Ping to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Ping from a ByteBuffer. */
  public static Ping fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public boolean reset;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Ping() {}

  /**
   * All-args constructor.
   * @param reset The new value for reset
   */
  public Ping(java.lang.Boolean reset) {
    this.reset = reset;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return reset;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: reset = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'reset' field.
   * @return The value of the 'reset' field.
   */
  public java.lang.Boolean getReset() {
    return reset;
  }

  /**
   * Sets the value of the 'reset' field.
   * @param value the value to set.
   */
  public void setReset(java.lang.Boolean value) {
    this.reset = value;
  }

  /**
   * Creates a new Ping RecordBuilder.
   * @return A new Ping RecordBuilder
   */
  public static com.oracle.hackson.webapp.Schema.avrotojava.Ping.Builder newBuilder() {
    return new com.oracle.hackson.webapp.Schema.avrotojava.Ping.Builder();
  }

  /**
   * Creates a new Ping RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Ping RecordBuilder
   */
  public static com.oracle.hackson.webapp.Schema.avrotojava.Ping.Builder newBuilder(com.oracle.hackson.webapp.Schema.avrotojava.Ping.Builder other) {
    return new com.oracle.hackson.webapp.Schema.avrotojava.Ping.Builder(other);
  }

  /**
   * Creates a new Ping RecordBuilder by copying an existing Ping instance.
   * @param other The existing instance to copy.
   * @return A new Ping RecordBuilder
   */
  public static com.oracle.hackson.webapp.Schema.avrotojava.Ping.Builder newBuilder(com.oracle.hackson.webapp.Schema.avrotojava.Ping other) {
    return new com.oracle.hackson.webapp.Schema.avrotojava.Ping.Builder(other);
  }

  /**
   * RecordBuilder for Ping instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Ping>
    implements org.apache.avro.data.RecordBuilder<Ping> {

    private boolean reset;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.oracle.hackson.webapp.Schema.avrotojava.Ping.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.reset)) {
        this.reset = data().deepCopy(fields()[0].schema(), other.reset);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Ping instance
     * @param other The existing instance to copy.
     */
    private Builder(com.oracle.hackson.webapp.Schema.avrotojava.Ping other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.reset)) {
        this.reset = data().deepCopy(fields()[0].schema(), other.reset);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'reset' field.
      * @return The value.
      */
    public java.lang.Boolean getReset() {
      return reset;
    }

    /**
      * Sets the value of the 'reset' field.
      * @param value The value of 'reset'.
      * @return This builder.
      */
    public com.oracle.hackson.webapp.Schema.avrotojava.Ping.Builder setReset(boolean value) {
      validate(fields()[0], value);
      this.reset = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'reset' field has been set.
      * @return True if the 'reset' field has been set, false otherwise.
      */
    public boolean hasReset() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'reset' field.
      * @return This builder.
      */
    public com.oracle.hackson.webapp.Schema.avrotojava.Ping.Builder clearReset() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Ping build() {
      try {
        Ping record = new Ping();
        record.reset = fieldSetFlags()[0] ? this.reset : (java.lang.Boolean) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Ping>
    WRITER$ = (org.apache.avro.io.DatumWriter<Ping>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Ping>
    READER$ = (org.apache.avro.io.DatumReader<Ping>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
